server.port: 8888
#spring.cloud.config.server.git.uri: https://github.com/zpng/spring-cloud-config-demo.git
#spring.cloud.config.server.git.searchPaths: cloud-config-repo
spring.cloud.config.server.git.searchPaths: cloud-config-repo
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
spring.application.name: cloud-config-server
spring:
  cloud:
    config:
      server:
        native:
          search-locations:
#spring:
#  rabbitmq:
#    host: localhost
#  datasource:
#    schema: classpath:/db.sql
#    url: jdbc:mysql://127.0.0.1/mytest
#    username: root
#    password: root
#     #Switch this on to create the schema on startup:
#    initialize: true
#    continueOnError: true


