spring.rabbitmq.host: 10.10.60.65
spring.rabbitmq.port: 5672
spring.rabbitmq.virtual-host: /
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

#turbine:
#  appConfig: cloud-simple-ui
#  clusterNameExpression: new String('default') #http://stackoverflow.com/questions/28365202/spring-boot-eureka-server-hystrix-with-turbine-empty-turbine-stream